app:
 build: ./app
 enviorment:
  - FLASK_APP="run.py"
  - APP_SETTINGS = "StagingConfig"
  - DATABASE_URL = "postgresql://localhost/flask_api"
  - SECRET = "TestSecret1111"
 ports:
  - "5000:80"
 volumes:
  - .:/code
